### ISSUE TITLE
ansi2html does not work with Python 3

### ISSUE THREAD

**Issue by legion80** [ralphbean/ansi2html#60]
I have a git hook that converts the diff to HTML and displays it in preparation of writing a good change log.

With Python 3.4, I get the follow error:

```
Traceback (most recent call last):
  File ".git/hooks/prepare-commit-msg", line 108, in <module>
    output_file_path = create_pretty_html_diff()
  File ".git/hooks/prepare-commit-msg", line 90, in create_pretty_html_diff
    html = html_converter.convert(output, full=False)
  File "/.../.virtualenvs/odev/lib/python3.4/site-packages/ansi2html/converter.py", line 415, in convert
    attrs = self.prepare(ansi, ensure_trailing_newline=ensure_trailing_newline)
  File "/.../.virtualenvs/odev/lib/python3.4/site-packages/ansi2html/converter.py", line 395, in prepare
    body = self.apply_regex(ansi)
  File "/.../.virtualenvs/odev/lib/python3.4/site-packages/ansi2html/converter.py", line 238, in apply_regex
    parts = self._collapse_cursor(parts)
  File "/.../.virtualenvs/odev/lib/python3.4/site-packages/ansi2html/converter.py", line 371, in _collapse_cursor
    for part in parts:
  File "/.../.virtualenvs/odev/lib/python3.4/site-packages/ansi2html/converter.py", line 266, in _apply_regex
    ansi = ansi.replace(pattern, special)
TypeError: 'str' does not support the buffer interface
```

From http://stackoverflow.com/questions/5471158/typeerror-str-does-not-support-the-buffer-interface it appears there needs to be a conversion to bytes.

**Comment by ysangkok** [comment]
It works great on my Python 3.4 installation. Could you do a [Short, Self Contained, Correct Example](http://sscce.org/)?

**Comment by ralphbean** [comment]
@legion80, are you still having this issue?  If so, can you give us an example so we can try to reproduce the failure?

**Comment by ralphbean** [comment]
OK.  I think this is fine.
