### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1854

### ISSUE THREAD

**Issue by seanchen** [ralphbean/ansi2html#62]
hi,

I am trying to convert the karma testing result to HTML.

Here is the karma report saved in txt file

```
> leocornus-nodejs-sandbox@0.0.6 gulp /usr/rd/leocornus-nodejs-sandbox
> gulp

[12:57:01] Using gulpfile /usr/rd/leocornus-nodejs-sandbox/gulpfile.js
[12:57:01] Starting 'karma'...
[12:57:01] Starting 'karma.jquery'...
[12:57:01] Starting 'jasmine'...
^[[32mINFO [karma]: ^[[39mKarma v0.12.37 server started at http://localhost:9876/
^[[32mINFO [launcher]: ^[[39mStarting browser Firefox
^[[32m.^[[0m

1 spec, 0 failures
Finished in 0 seconds
[12:57:01] Finished 'jasmine' after 89 ms
^[[33mWARN [karma]: ^[[39mPort 9876 in use
^[[32mINFO [karma]: ^[[39mKarma v0.12.37 server started at http://localhost:9877/
^[[32mINFO [launcher]: ^[[39mStarting browser Firefox
^[[32mINFO [Firefox 30.0.0 (Ubuntu 0.0.0)]: ^[[39mConnected on socket eMzdhfb30orKKWXBiMlS with id 97169530
^[[32mINFO [Firefox 30.0.0 (Ubuntu 0.0.0)]: ^[[39mConnected on socket WomLA0aSM7sr7wiSiMlG with id 72190175

^[[4m^[[1mStart:^[[22m^[[24m
^[[1m  A suite^[[22m
^[[32m    ^[[32m✔^[[32m contains a pect with an expectation^[[39m
.
Firefox 30.0.0 (Ubuntu 0.0.0): Executed 1 of 1 SUCCESS (0.003 secs / 0.001 secs)

^[[32mFinished in 0.003 secs / 0.001 secs^[[39m

^[[4m^[[1mSUMMARY:^[[22m^[[24m
^[[32m^[[32m✔^[[32m 1 test completed^[[39m
[12:57:05] Finished 'karma' after 3.74 s

^[[4m^[[1mStart:^[[22m^[[24m
^[[1m  Testing Bootstrap Form^[[22m
^[[32m    ^[[32m✔^[[32m testing query and search^[[39m
^[[1m    try the sub section of a spec^[[22m
^[[32m      ^[[32m✔^[[32m testing query and add class^[[39m
^[[1m  Testing Bootstrap Modal^[[22m
^[[32m    ^[[32m✔^[[32m testing show and hide modal^[[39m
^[[1m  Testing Bootstrap Basic^[[22m
^[[32m    ^[[32m✔^[[32m testing find method^[[39m
^[[32m    ^[[32m✔^[[32m testing data-toggle^[[39m
^[[1m  Testing jquery from HTML fixture^[[22m
^[[32m    ^[[32m✔^[[32m testing jquery selector^[[39m
^[[32m    ^[[32m✔^[[32m testing jquery functions^[[39m
^[[1m  Testing jQuery Basic^[[22m
^[[32m    ^[[32m✔^[[32m simple jquery object^[[39m
^[[32m    ^[[32m✔^[[32m simple DOM element^[[39m
^[[32m    ^[[32m✔^[[32m some jQuery method^[[39m
LOG: 'desc: sandbox plugin'
LOG: 'id: divid'
ALERT: 'div inner html'
^[[1m  simple jquery plugin test^[[22m
^[[32m    ^[[32m✔^[[32m testing plugin click event^[[39m

^[[32mFinished in 0.127 secs / 0.123 secs^[[39m

^[[4m^[[1mSUMMARY:^[[22m^[[24m
^[[32m^[[32m✔^[[32m 11 tests completed^[[39m
[12:57:05] Finished 'karma.jquery' after 3.85 s
[12:57:05] Starting 'default'...
[12:57:05] Finished 'default' after 9.64 μs
```

My code is very simple

```python
>>> npm_file = open('/tmp/npm.txt', 'r')                            
>>> npm = " ".join(npm_file.read())                                 
>>> npm_html = conv.convert(npm);
>>> npm_file = open('/tmp/npm.html', 'w')                           
>>> try:
...     npm_file.write(npm_html)                                    
... finally:
...     npm_file.close()
```

I got the following error message:

```
Failed example:
    npm_html = conv.convert(npm);
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest README.rst[18]>", line 1, in <module>
        npm_html = conv.convert(npm);
      File "/usr/rd/cfgrepo/sample/python/eggs/ansi2html-1.1.0-py2.7.egg/ansi2html/converter.py", line 428, in convert
        'output_encoding' : self.output_encoding,
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1854: ordinal not in range(128)
```

could anybody help solve this issue?

thanks,

Sean

**Comment by ralphbean** [comment]
First question:  what is the encoding of ``/tmp/npm.txt``?  Your shell might be able to tell you with:

```bash
$ file /tmp/npm.txt
```

**Comment by ralphbean** [comment]
Does this do it for you?

```python
import ansi2html

conv = ansi2html.Ansi2HTMLConverter()

with open('/tmp/npm.txt', 'rb') as npm_file:
    # Read raw bytes and convert to unicode
    npm = npm_file.read().decode('utf-8')

npm_html = conv.convert(npm)

with open('/tmp/npm.html', 'wb') as npm_file:
    # Convert back from unicode to raw bytes
    npm_file.write(npm_html.encode('utf-8'))
```

**Comment by seanchen** [comment]
Thanks a lot, @ralphbean

it works perfectly! I learned how to handle it now

BTW, the npm.txt has the following encoding.

```
/tmp/npm.txt: UTF-8 Unicode text, with escape sequences
```

**Comment by ralphbean** [comment]
Cheers!
